/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-12-11 07:45:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.public_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.User;
import util.CategoriesUtil;
import models.CatPerfume;
import java.util.ArrayList;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/templates/public/inc/library/libraryFooter.jsp", Long.valueOf(1606893433288L));
    _jspx_dependants.put("/templates/public/inc/footer.jsp", Long.valueOf(1607614348187L));
    _jspx_dependants.put("/templates/public/inc/library/libraryHeader.jsp", Long.valueOf(1606893302457L));
    _jspx_dependants.put("/templates/public/inc/header.jsp", Long.valueOf(1607220766604L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("util.CategoriesUtil");
    _jspx_imports_classes.add("models.CatPerfume");
    _jspx_imports_classes.add("models.User");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from wow-themes.com/demo/html/perfume/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 19 Aug 2015 06:47:57 GMT -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("  <title>Shop Nước Hoa</title>\r\n");
      out.write("\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/flaticon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/owl.carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/owl.transitions.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/rs-plugin/css/settings.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/color.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- JQUERY -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/dist/js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("  <![endif]-->");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"pageWrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t");

			if(session.getAttribute("userInfor") != null){
				User userInfor = (User) session.getAttribute("userInfor");
				
      out.write("<div class=\"tp-bar\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<ul class=\"tp-links\">\r\n");
      out.write("\t\t\t\t\t<li><span class=\"dropBox-btn\">Xin chào &nbsp; ");
      out.print(userInfor.getFullname() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- /tp-links -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

			}else{
				
      out.write("<div class=\"tp-bar\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<ul class=\"tp-links\">\r\n");
      out.write("\t\t\t\t\t<li><span class=\"dropBox-btn\">Đăng nhập <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"caret caret-cut\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropBox\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box-section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>Bạn đã có tài khoản - Đăng nhập</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form class=\"accounts-form clearfix\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"username\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Email Address\" required/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Password\" required/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-default text-uppercase\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Đăng nhập\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /accounts-form -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"help-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Quên tài khoản?</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /box-section -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box-section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>Chưa có tài khoản - Đăng ký</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"list-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>Tôi muốn trở thành khách hàng vip</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>Tôi muốn thanh toán nhanh</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form class=\"accounts-form clearfix\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/signup\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Họ và tên\" name=\"fullname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Email\" name=\"\"username\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" placeholder=\"mật khẩu\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-default text-uppercase\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Đăng ký\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /accounts-form -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /box-section -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /dropBox --></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- /tp-links -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");
	
			}
		
      out.write("<!-- /tp-bar -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"main-bar\">\r\n");
      out.write("\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t<a href=\"index-2.html\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo.png\"\r\n");
      out.write("\t\t\t\t\talt=\"perfume\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /logo -->\r\n");
      out.write("\t\t\t<div class=\"user-controls-bar\">\r\n");
      out.write("\t\t\t\t<ul class=\"user-controls\">\r\n");
      out.write("\t\t\t\t\t<li><span class=\"site-search-btn dropBox-btn\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"flaticon-magnifier56\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropBox\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box-section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form class=\"accounts-form clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"search\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Search Key\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-default text-uppercase\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Tìm kiếm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /accounts-form -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /box-section -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /dropBox --></li>\r\n");
      out.write("\t\t\t\t\t<li><span class=\"cart-btn dropBox-btn\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"flaticon-shopping191\"></i><span class=\"badge\">0</span></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropBox\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box-section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"cart-info-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"cart-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"cart-item-bx\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/resource/img-1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Thierry Mugler Alien</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>loại 30ml</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>$45.99</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"tot\">$45.99</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- /cart-item-bx -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--/ cart-info-list -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/paypal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-dark btn-block dismiss-button\">Thanh toán</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Giao hàng miễn phí khi mua từ trên 3 sản phẩm</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /cart-info-box -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- empty cart message -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"box-section\">\r\n");
      out.write("              <h6>Your Cart is empty</h6>\r\n");
      out.write("              <a href=\"#\" class=\"btn btn-dark btn-block dismiss-button\">Continue Shopping</a>\r\n");
      out.write("              <p>Enjoy complimentary shipping on all orders over $75 and also complimentary samples and returns with every order.</p>\r\n");
      out.write("            </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /cart-info-box -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /dropBox --></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"toggle-menu\">\r\n");
      out.write("\t\t\t\t\t\t<button data-target=\".navbar-collapse\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"navbar-toggle\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- /user-controls -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /user-controls -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"main-nav-bar\">\r\n");
      out.write("\t\t\t\t<nav class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"main-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/home\">Trang chủ</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/home\">Thương hiệu</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

							if (request.getAttribute("catPFList") != null) {
							ArrayList<CatPerfume> catPFList = (ArrayList<CatPerfume>) request.getAttribute("catPFList");
							if (catPFList.size() > 0) {
								// lấy toàn bộ list, kiểm tra nếu id cha = 0 (cấp cao nhất) => view ra
								for (CatPerfume cat : catPFList) {
							// kiểm tra
							if (cat.getParrent_id() == 0) {
						
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/cat?id=");
      out.print(cat.getId());
      out.write('"');
      out.write('>');
      out.print(cat.getCatPerfume());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								CategoriesUtil.showBrand(cat.getId(), request, out);
							}
							}
							
      out.write("</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/blog\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/contact\">Liên\r\n");
      out.write("\t\t\t\t\t\t\t\thệ</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t");

					}
				}
				
      out.write("</div>\r\n");
      out.write("\t\t\t<!-- /main-nav-bar -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /main-bar -->");
      out.write("<section class=\"section-banner\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <ul class=\"breadcrumb\">\n");
      out.write("        <li><a href=\"#\">Trang chủ</a></li>\n");
      out.write("        <li class=\"active\">Liên hệ</li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("  </section><!-- /section-banner -->\n");
      out.write("\n");
      out.write("  <section class=\"section-compact\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"cart-block\">\n");
      out.write("        <header class=\"heading-3 page-heading\">\n");
      out.write("          <h4>Câu hỏi? Kích vào đây để xem các câu hỏi thường gặp <span class=\"text-primary\">FAQ</span></h4>\n");
      out.write("        </header>\n");
      out.write("        \n");
      out.write("        <div class=\"form-main-container\">\n");
      out.write("        ");

		if(!"".equals(request.getParameter("msg"))){
			String msg = request.getParameter("msg");
			if("OK".equals(msg)){
				
      out.write("<div class=\"alert alert-success\" role=\"alert\">\n");
      out.write("\t\t\t\t\t\t Cảm ơn bạn đã phản hồi cho chúng tôi. Chúc bạn có một ngày tràn đầy niềm vui.!\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t");

			}
		}
	
      out.write("<div class=\"row\">\n");
      out.write("            <div class=\"col-sm-5 col-lg-4\">\n");
      out.write("              <header class=\"heading-5\">\n");
      out.write("                <h4>01/</h4>\n");
      out.write("                <span>Liên hệ <br>Chúng tôi</span>\n");
      out.write("              </header>\n");
      out.write("              <ul class=\"contact-list\">\n");
      out.write("                <li><span class=\"iconic\"><i class=\"flaticon-call36\"></i></span>0797 - 207 - 493</li>\n");
      out.write("                <li><span class=\"iconic\"><i class=\"flaticon-email15\"></i></span><a href=\"#\">leducnam1805@gmail.com</a></li>\n");
      out.write("                <li><span class=\"iconic\"><i class=\"flaticon-twitter16\"></i></span><a href=\"#\">@followperfume</a></li>\n");
      out.write("                <li><span class=\"iconic\"><i class=\"flaticon-facebook43\"></i></span><a href=\"#\">facebook.com/perfume</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-7 col-lg-8\">\n");
      out.write("              <div class=\"form-section-box\">\n");
      out.write("                <header class=\"heading-5 text-center\">\n");
      out.write("                  <h4>02/</h4>\n");
      out.write("                  <span>Gửi liên hệ <br>cho chúng tôi</span>\n");
      out.write("                </header>\n");
      out.write("\n");
      out.write("                <form class=\"checkout-form\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/contact\">\n");
      out.write("                ");

		        	if(request.getAttribute("err") != null){
		        		
      out.write("<div class=\"alert alert-danger\" role=\"alert\">\n");
      out.write("\t\t\t\t\t\t\t\t  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${err}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t        \t\t");

		        	}
		        
      out.write("<div class=\"form-group row\">\n");
      out.write("                    <label class=\"col-md-2 label-md\">Tên*</label>\n");
      out.write("                    <div class=\"col-md-10\">\n");
      out.write("                      <input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"class=\"form-control\" placeholder=\"Name\" name=\"name\">\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group row\">\n");
      out.write("                    <label class=\"col-md-2 label-md\">Email</label>\n");
      out.write("                    <div class=\"col-md-10\">\n");
      out.write("                      <input type=\"email\" class=\"form-control\" placeholder=\"Email Address\"name=\"email\">\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group row\">\n");
      out.write("                    <label class=\"col-md-2 label-md\">Số liên lạc*</label>\n");
      out.write("                    <div class=\"col-md-10\">\n");
      out.write("                      <input type=\"text\" class=\"form-control\" placeholder=\"Phone\" name=\"phone\">\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group row\">\n");
      out.write("                    <label class=\"col-md-2 label-md\">Lời nhắn</label>\n");
      out.write("                    <div class=\"col-md-10\">\n");
      out.write("                      <textarea class=\"form-control\" placeholder=\"Comments\" name=\"message\"></textarea>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <p class=\"text-center\"><input type=\"submit\" class=\"btn btn-default btn-lg\" value=\"Gửi\"></p>\n");
      out.write("                </form>\n");
      out.write("              </div><!-- /form-section-box -->\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div><!-- /form-main-container -->\n");
      out.write("\n");
      out.write("      </div><!-- /cart-block -->\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("\t<section class=\"section-focus bg-dark\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"promo-box\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\n");
      out.write("\t\t\t\t\t\t<p><strong>Phần thưởng</strong> - Tham gia đánh giá sản phẩm để nhận phần thưởng</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3\">\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-default btn-lg\">Bắt đầu đánh giá</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("<section class=\"section footer-widgets bg-lighter-grey\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget widget-info\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"widget-heading-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><i class=\"flaticon-help\"></i>Câu hỏi?</h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<p>Liên hệ chúng tôi.</p>\r\n");
      out.write("\t\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"flaticon-phone72\"></i>0797 - 207 - 493</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"flaticon-email15\"></i>leducnam1805@gmail.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"flaticon-google125\"></i>Bạn có muốn nói chuyện trực tiếp?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget widget-info\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"widget-heading-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><i class=\"flaticon-shield90\"></i>Bảo mật</h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<p>Chính sách đơn giản.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Xác minh tính xác thực</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Bảo vệ quyền riêng tư</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget widget-info\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"widget-heading-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><i class=\"flaticon-shipping\"></i>Giao hàng</h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<p>Miễn phí khi mua 3 Sản phẩm.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Bao bì đẹp</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Kiểm tra hàng trước khi nhận</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget widget-info\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"widget-heading-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><i class=\"flaticon-creditcard21\"></i>Thanh toán</h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-cards\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo-visa.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo-americanexpress.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo-mastercard.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo-amazon.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo-paypal.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<footer class=\"site-footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("      <nav>\r\n");
      out.write("        <ul class=\"footer-links\">\r\n");
      out.write("          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/home\">Trang chủ</a></li>\r\n");
      out.write("          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/thuong-hieu\">Thương hiệu</a></li>\r\n");
      out.write("          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/blog\">Blog</a></li>\r\n");
      out.write("          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/lien-he\">Liên hệ</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</div><!-- /pageWrap -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"preloader-container\">\r\n");
      out.write("  <div id=\"loading-center-absolute\">\r\n");
      out.write("    <div class=\"object\" id=\"object_one\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_two\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_three\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_four\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_five\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_six\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_seven\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_eight\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_big\"></div>\r\n");
      out.write("  </div><!-- /loading-center-absolute -->\r\n");
      out.write("</div><!-- /preloader-container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript\r\n");
      out.write("================================================== -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/plugins.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- revolution slider plugin -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/rs-plugin/js/jquery.themepunch.tools.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/rs-plugin/js/jquery.themepunch.revolution.min.js\"></script>\r\n");
      out.write("<!-- sweetalert -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/dist/node_modules/sweetalert2/dist/sweetalert2.all.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("  var revapi;\r\n");
      out.write("\r\n");
      out.write("  jQuery(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("       revapi = jQuery('.tp-banner').revolution({\r\n");
      out.write("\r\n");
      out.write("        dottedOverlay:\"none\",\r\n");
      out.write("        delay:9000,\r\n");
      out.write("        startwidth:1170,\r\n");
      out.write("        startheight:700,\r\n");
      out.write("        hideThumbs:200,\r\n");
      out.write("        \r\n");
      out.write("        thumbWidth:100,\r\n");
      out.write("        thumbHeight:50,\r\n");
      out.write("        thumbAmount:5,\r\n");
      out.write("        \r\n");
      out.write("        navigationType:\"none\",\r\n");
      out.write("        navigationArrows:\"solo\",\r\n");
      out.write("        navigationStyle:\"\",\r\n");
      out.write("        \r\n");
      out.write("        touchenabled:\"on\",\r\n");
      out.write("        onHoverStop:\"on\",\r\n");
      out.write("        \r\n");
      out.write("        swipe_velocity: 0.7,\r\n");
      out.write("        swipe_min_touches: 1,\r\n");
      out.write("        swipe_max_touches: 1,\r\n");
      out.write("        drag_block_vertical: false,\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("        keyboardNavigation:\"on\",\r\n");
      out.write("        \r\n");
      out.write("        navigationHAlign:\"center\",\r\n");
      out.write("        navigationVAlign:\"bottom\",\r\n");
      out.write("        navigationHOffset:0,\r\n");
      out.write("        navigationVOffset:20,\r\n");
      out.write("\r\n");
      out.write("        soloArrowLeftHalign:\"left\",\r\n");
      out.write("        soloArrowLeftValign:\"center\",\r\n");
      out.write("        soloArrowLeftHOffset:20,\r\n");
      out.write("        soloArrowLeftVOffset:0,\r\n");
      out.write("\r\n");
      out.write("        soloArrowRightHalign:\"right\",\r\n");
      out.write("        soloArrowRightValign:\"center\",\r\n");
      out.write("        soloArrowRightHOffset:20,\r\n");
      out.write("        soloArrowRightVOffset:0,\r\n");
      out.write("            \r\n");
      out.write("        shadow:0,\r\n");
      out.write("        fullWidth:\"on\",\r\n");
      out.write("        fullScreen:\"off\",\r\n");
      out.write("\r\n");
      out.write("        spinner:\"spinner0\",\r\n");
      out.write("        \r\n");
      out.write("        stopLoop:\"off\",\r\n");
      out.write("        stopAfterLoops:-1,\r\n");
      out.write("        stopAtSlide:-1,\r\n");
      out.write("\r\n");
      out.write("        shuffle:\"off\",\r\n");
      out.write("                            \r\n");
      out.write("        forceFullWidth:\"off\",           \r\n");
      out.write("        fullScreenAlignForce:\"off\",           \r\n");
      out.write("        minFullScreenHeight:\"400\",            \r\n");
      out.write("                    \r\n");
      out.write("        hideThumbsOnMobile:\"off\",\r\n");
      out.write("        hideNavDelayOnMobile:1500,            \r\n");
      out.write("        hideBulletsOnMobile:\"off\",\r\n");
      out.write("        hideArrowsOnMobile:\"off\",\r\n");
      out.write("        hideThumbsUnderResolution:0,\r\n");
      out.write("        \r\n");
      out.write("        hideSliderAtLimit:0,\r\n");
      out.write("        hideCaptionAtLimit:0,\r\n");
      out.write("        hideAllCaptionAtLilmit:0,\r\n");
      out.write("        startWithSlide:0,\r\n");
      out.write("        fullScreenOffsetContainer: \"\"\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("  }); //ready\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from wow-themes.com/demo/html/perfume/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 19 Aug 2015 06:49:09 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
