/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-12-13 07:53:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.public_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.Perfume;
import models.Picture;
import java.util.List;
import models.Item;
import java.util.List;
import models.Order;
import models.User;
import util.CategoriesUtil;
import models.CatPerfume;
import java.util.ArrayList;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/templates/public/inc/library/libraryFooter.jsp", Long.valueOf(1606893433288L));
    _jspx_dependants.put("/templates/public/inc/slide.jsp", Long.valueOf(1604898080181L));
    _jspx_dependants.put("/templates/public/inc/footer.jsp", Long.valueOf(1607614348187L));
    _jspx_dependants.put("/templates/public/inc/library/libraryHeader.jsp", Long.valueOf(1607846012855L));
    _jspx_dependants.put("/templates/public/inc/header.jsp", Long.valueOf(1607741914067L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.Perfume");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("util.CategoriesUtil");
    _jspx_imports_classes.add("models.Item");
    _jspx_imports_classes.add("models.CatPerfume");
    _jspx_imports_classes.add("models.User");
    _jspx_imports_classes.add("models.Picture");
    _jspx_imports_classes.add("models.Order");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from wow-themes.com/demo/html/perfume/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 19 Aug 2015 06:47:57 GMT -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("  <title>Shop Nước Hoa</title>\r\n");
      out.write("\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/flaticon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/owl.carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/owl.transitions.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/rs-plugin/css/settings.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/css/color.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- JQUERY -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/dist/js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("  <!-- paypal -->\r\n");
      out.write("  <script src=\"https://www.paypal.com/sdk/js?client-id=sb\"></script>\r\n");
      out.write("\t<script>paypal.Buttons().render('body');</script>\r\n");
      out.write("\t <!-- paypal -->\r\n");
      out.write("  <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("  <![endif]-->");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"pageWrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t");

			if(session.getAttribute("userInfor") != null){
				User userInfor = (User) session.getAttribute("userInfor");
				
      out.write("<div class=\"tp-bar\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<ul class=\"tp-links\">\r\n");
      out.write("\t\t\t\t\t<li><span class=\"dropBox-btn\">Xin chào &nbsp; ");
      out.print(userInfor.getFullname() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- /tp-links -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

			}else{
				
      out.write("<div class=\"tp-bar\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<ul class=\"tp-links\">\r\n");
      out.write("\t\t\t\t\t<li><span class=\"dropBox-btn\">Đăng nhập <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"caret caret-cut\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropBox\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box-section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>Bạn đã có tài khoản - Đăng nhập</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form class=\"accounts-form clearfix\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"username\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Email Address\" required/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Password\" required/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-default text-uppercase\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Đăng nhập\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /accounts-form -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"help-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Quên tài khoản?</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /box-section -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box-section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>Chưa có tài khoản - Đăng ký</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"list-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>Tôi muốn trở thành khách hàng vip</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>Tôi muốn thanh toán nhanh</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form class=\"accounts-form clearfix\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/signup\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Họ và tên\" name=\"fullname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Email\" name=\"username\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" placeholder=\"mật khẩu\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-default text-uppercase\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Đăng ký\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /accounts-form -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /box-section -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /dropBox --></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- /tp-links -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");
	
			}
		
      out.write("<!-- /tp-bar -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"main-bar\">\r\n");
      out.write("\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t<a href=\"index-2.html\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo.png\"\r\n");
      out.write("\t\t\t\t\talt=\"perfume\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /logo -->\r\n");
      out.write("\t\t\t<div class=\"user-controls-bar\">\r\n");
      out.write("\t\t\t\t<ul class=\"user-controls\">\r\n");
      out.write("\t\t\t\t\t<li><span class=\"site-search-btn dropBox-btn\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"flaticon-magnifier56\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropBox\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box-section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form class=\"accounts-form clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"search\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Search Key\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-default text-uppercase\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Tìm kiếm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /accounts-form -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /box-section -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /dropBox --></li>\r\n");
      out.write("\t\t\t\t\t\t");

							if(session.getAttribute("order") != null){
								Order order = (Order) session.getAttribute("order");
								List<Item> listItem = (List<Item>) order.getItem();
								if(listItem.size() > 0){
									
      out.write("<li>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"cart-btn dropBox-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"flaticon-shopping191\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t");

								int total = 0;
								for(Item quantity : listItem){
									int totalFinal = 0;
									total += quantity.getQuantity();
									totalFinal += total;
									
      out.write("<span class=\"badge\">");
      out.print(totalFinal );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

								}
							
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropBox\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box-section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"cart-info-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for(Item item : listItem){
										Long tong = 0L;
										int quanity = item.getQuantity();
										Long price = item.getProduct().getMoney();
										tong = quanity * price;
										
      out.write("<li class=\"cart-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"cart-item-bx\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/resource/img-1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">");
      out.print(item.getProduct().getPerfumes() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Số Lượng: ");
      out.print(item.getQuantity() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>");
      out.print(item.getProduct().getCapacity() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>$");
      out.print(price );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"tot\">$");
      out.print(tong );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- /cart-item-bx -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

									}
								
      out.write("</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--/ cart-info-list -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/order\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-dark btn-block dismiss-button\">Giỏ hàng</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Giao hàng miễn phí khi mua từ trên 3 sản phẩm</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /cart-info-box -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- empty cart message -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"box-section\">\r\n");
      out.write("              <h6>Your Cart is empty</h6>\r\n");
      out.write("              <a href=\"#\" class=\"btn btn-dark btn-block dismiss-button\">Continue Shopping</a>\r\n");
      out.write("              <p>Enjoy complimentary shipping on all orders over $75 and also complimentary samples and returns with every order.</p>\r\n");
      out.write("            </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /cart-info-box -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /dropBox --></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

								}
							}
						
      out.write("<li class=\"toggle-menu\">\r\n");
      out.write("\t\t\t\t\t\t<button data-target=\".navbar-collapse\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"navbar-toggle\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- /user-controls -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /user-controls -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"main-nav-bar\">\r\n");
      out.write("\t\t\t\t<nav class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"main-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/home\">Trang chủ</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/home\">Thương hiệu</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

							if (request.getAttribute("catPFList") != null) {
							ArrayList<CatPerfume> catPFList = (ArrayList<CatPerfume>) request.getAttribute("catPFList");
							if (catPFList.size() > 0) {
								// lấy toàn bộ list, kiểm tra nếu id cha = 0 (cấp cao nhất) => view ra
								for (CatPerfume cat : catPFList) {
							// kiểm tra
							if (cat.getParrent_id() == 0) {
						
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/cat?id=");
      out.print(cat.getId());
      out.write('"');
      out.write('>');
      out.print(cat.getCatPerfume());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								CategoriesUtil.showBrand(cat.getId(), request, out);
							}
							}
							
      out.write("</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/blog\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/contact\">Liên\r\n");
      out.write("\t\t\t\t\t\t\t\thệ</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t");

					}
				}
				
      out.write("</div>\r\n");
      out.write("\t\t\t<!-- /main-nav-bar -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /main-bar -->");
      out.write("<div class=\"tp-banner-container pattern-1\">\r\n");
      out.write("    <div class=\"tp-banner\">\r\n");
      out.write("      <ul>\r\n");
      out.write("\r\n");
      out.write("        <li data-transition=\"fade\" data-slotamount=\"5\" data-masterspeed=\"700\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"tp-caption text-medium skewfromrightshort tp-resizeme rs-parallaxlevel-0\"\r\n");
      out.write("            data-x=\"0\"\r\n");
      out.write("            data-hoffset=\"0\"\r\n");
      out.write("            data-y=\"center\"\r\n");
      out.write("            data-voffset=\"-50\"\r\n");
      out.write("\r\n");
      out.write("            data-easing=\"Power3.easeInOut\"\r\n");
      out.write("            data-splitin=\"chars\"\r\n");
      out.write("            data-splitout=\"none\"\r\n");
      out.write("            data-elementdelay=\"0.1\"\r\n");
      out.write("            data-endelementdelay=\"0.1\"\r\n");
      out.write("\r\n");
      out.write("            data-speed=\"1000\"\r\n");
      out.write("            data-start=\"500\"\r\n");
      out.write("            data-endspeed=\"300\">Hương thơm mới cho phái mạnh\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tp-caption text-larger customin customout start\"\r\n");
      out.write("            data-x=\"0\"\r\n");
      out.write("            data-hoffset=\"0\"\r\n");
      out.write("            data-y=\"center\"\r\n");
      out.write("            data-voffset=\"0\"\r\n");
      out.write("\r\n");
      out.write("            data-customin=\"x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;\"\r\n");
      out.write("            data-customout=\"x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;\"\r\n");
      out.write("\r\n");
      out.write("            data-speed=\"1000\"\r\n");
      out.write("            data-start=\"500\"\r\n");
      out.write("            data-easing=\"Power3.easeInOut\"\r\n");
      out.write("            data-endspeed=\"300\">Aventus Creed\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"tp-caption text-medium customin randomrotateout tp-resizeme rs-parallaxlevel-1\"\r\n");
      out.write("            data-x=\"left\"\r\n");
      out.write("            data-hoffset=\"400\"\r\n");
      out.write("            data-y=\"center\"\r\n");
      out.write("            data-voffset=\"50\"\r\n");
      out.write("\r\n");
      out.write("            data-customin=\"x:0;y:100;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:1;scaleY:3;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:0% 0%;\"\r\n");
      out.write("\r\n");
      out.write("            data-speed=\"500\"\r\n");
      out.write("            data-start=\"1400\"\r\n");
      out.write("            data-easing=\"Power3.easeInOut\"\r\n");
      out.write("            data-splitin=\"chars\"\r\n");
      out.write("            data-splitout=\"none\"\r\n");
      out.write("            data-elementdelay=\"0.1\"\r\n");
      out.write("            data-endelementdelay=\"0.1\"\r\n");
      out.write("            data-endspeed=\"600\">Trở nên lịch lãm\r\n");
      out.write("\r\n");
      out.write("          <div class=\"tp-caption lfr rs-parallaxlevel-2 side-image\"\r\n");
      out.write("            data-x=\"right\"\r\n");
      out.write("            data-y=\"top\"\r\n");
      out.write("            data-speed=\"2000\"\r\n");
      out.write("            data-start=\"1000\"\r\n");
      out.write("            data-easing=\"Power4.easeOut\"\r\n");
      out.write("            data-elementdelay=\"0.1\"\r\n");
      out.write("            data-endelementdelay=\"0.1\"\r\n");
      out.write("            data-endspeed=\"500\"\r\n");
      out.write("            style=\"z-index: -1;\">\r\n");
      out.write("              <div class=\"rs-pulse\"  data-easing=\"Power4.easeInOut\" data-speed=\"1\" data-zoomstart=\"1\" data-zoomend=\"1.1\">\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/resource/dummy.png\" data-lazyload=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/resource/img-slider-1.png\" alt=\"image\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        </li>\r\n");
      out.write("        <li data-transition=\"boxslide,slotslide-horizontal,slotslide-vertical,curtain-1,cube,cube-horizontal,flyin\" data-slotamount=\"7\" data-masterspeed=\"300\"  data-saveperformance=\"off\"  class=\"slide1 slide3\">\r\n");
      out.write("    <!-- MAIN IMAGE -->\r\n");
      out.write("    <img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/resource/img-slider-2.png\"  alt=\"slide3\"  data-bgposition=\"center top\" data-bgfit=\"cover\" data-bgrepeat=\"no-repeat\">\r\n");
      out.write("    <!-- LAYERS -->\r\n");
      out.write("\r\n");
      out.write("    <!-- LAYER NR. 1 -->\r\n");
      out.write("    <div class=\"tp-caption lfl ltl tp-resizeme\" \r\n");
      out.write("       data-x=\"721\" \r\n");
      out.write("       data-y=\"154\"  \r\n");
      out.write("      data-speed=\"300\" \r\n");
      out.write("      data-start=\"500\" \r\n");
      out.write("      data-easing=\"Power3.easeInOut\" \r\n");
      out.write("      data-splitin=\"none\" \r\n");
      out.write("      data-splitout=\"none\" \r\n");
      out.write("      data-elementdelay=\"0.1\" \r\n");
      out.write("      data-endelementdelay=\"0.1\" \r\n");
      out.write("       data-endspeed=\"300\" \r\n");
      out.write("\r\n");
      out.write("      style=\"z-index: 5; max-width: auto; max-height: auto; white-space: nowrap;\"><p class=\"text-left\">Hương thơm mới cho phụ nữ</p> \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- LAYER NR. 2 -->\r\n");
      out.write("    <div class=\"tp-caption lfr ltl tp-resizeme\" \r\n");
      out.write("       data-x=\"725\" \r\n");
      out.write("       data-y=\"203\"  \r\n");
      out.write("      data-speed=\"300\" \r\n");
      out.write("      data-start=\"950\" \r\n");
      out.write("      data-easing=\"Power3.easeInOut\" \r\n");
      out.write("      data-splitin=\"none\" \r\n");
      out.write("      data-splitout=\"none\" \r\n");
      out.write("      data-elementdelay=\"0.1\" \r\n");
      out.write("      data-endelementdelay=\"0.1\" \r\n");
      out.write("       data-end=\"8650\" \r\n");
      out.write(" data-endspeed=\"300\" \r\n");
      out.write("\r\n");
      out.write("      style=\"z-index: 6; max-width: auto; max-height: auto; white-space: nowrap;\"><h1>Quý cô quyến rũ</h1> \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- LAYER NR. 3 -->\r\n");
      out.write("    <div class=\"tp-caption lft ltl tp-resizeme\" \r\n");
      out.write("       data-x=\"1006\" \r\n");
      out.write("       data-y=\"275\"  \r\n");
      out.write("      data-speed=\"300\" \r\n");
      out.write("      data-start=\"1500\" \r\n");
      out.write("      data-easing=\"Power3.easeInOut\" \r\n");
      out.write("      data-splitin=\"none\" \r\n");
      out.write("      data-splitout=\"none\" \r\n");
      out.write("      data-elementdelay=\"0.1\" \r\n");
      out.write("      data-endelementdelay=\"0.1\" \r\n");
      out.write("       data-endspeed=\"300\" \r\n");
      out.write("\r\n");
      out.write("      style=\"z-index: 7; max-width: auto; max-height: auto; white-space: nowrap;\"><p class=\"text-right\">Mùi hương thanh lịch</p> \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- LAYER NR. 4 -->\r\n");
      out.write("    <div class=\"tp-caption lfb ltl tp-resizeme\" \r\n");
      out.write("       data-x=\"728\" \r\n");
      out.write("       data-y=\"337\"  \r\n");
      out.write("      data-speed=\"300\" \r\n");
      out.write("      data-start=\"2000\" \r\n");
      out.write("      data-easing=\"Power3.easeInOut\" \r\n");
      out.write("      data-splitin=\"none\" \r\n");
      out.write("      data-splitout=\"none\" \r\n");
      out.write("      data-elementdelay=\"0.1\" \r\n");
      out.write("      data-endelementdelay=\"0.1\" \r\n");
      out.write("       data-endspeed=\"300\" \r\n");
      out.write("\r\n");
      out.write("      style=\"z-index: 8; max-width: auto; max-height: auto; white-space: nowrap;\"><a class=\"btn btn-default slide_button\" href=\"#\">Bắt đầu mua sắm</a> \r\n");
      out.write("    </div>\r\n");
      out.write("  </li>\r\n");
      out.write("<li data-transition=\"random\" data-slotamount=\"7\" data-masterspeed=\"300\"  data-saveperformance=\"off\" >\r\n");
      out.write("    <!-- MAIN IMAGE -->\r\n");
      out.write("    <img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/resource/img-slider-3.png\"  alt=\"slide4\"  data-bgposition=\"center top\" data-bgfit=\"cover\" data-bgrepeat=\"no-repeat\">\r\n");
      out.write("    <!-- LAYERS -->\r\n");
      out.write("\r\n");
      out.write("    <!-- LAYER NR. 1 -->\r\n");
      out.write("    <div class=\"tp-caption black tp-fade tp-resizeme\" \r\n");
      out.write("       data-x=\"656\" \r\n");
      out.write("       data-y=\"185\"  \r\n");
      out.write("      data-speed=\"300\" \r\n");
      out.write("      data-start=\"500\" \r\n");
      out.write("      data-easing=\"Power3.easeInOut\" \r\n");
      out.write("      data-splitin=\"none\" \r\n");
      out.write("      data-splitout=\"none\" \r\n");
      out.write("      data-elementdelay=\"0.1\" \r\n");
      out.write("      data-endelementdelay=\"0.1\" \r\n");
      out.write("       data-endspeed=\"300\" \r\n");
      out.write("\r\n");
      out.write("      style=\"z-index: 5; max-width: auto; max-height: auto; white-space: nowrap;\"><div class=\"slide1 slide4\">\r\n");
      out.write("\t<p class=\"text-left\">Hương thơm mới cho phụ nữ</p>\r\n");
      out.write("\t<h1>CHANEL COCO MADEMOISELLE</h1>\r\n");
      out.write("\t<p class=\"text-right\">Mùi hương thanh lịch</p>\r\n");
      out.write("\t<a class=\"btn btn-default slide_button\" href=\"#\">Bắt đầu mua sắm</a> \r\n");
      out.write("\r\n");
      out.write("</div> \r\n");
      out.write("    </div>\r\n");
      out.write("  </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"tp-bannertimer\"></div>\r\n");
      out.write("\r\n");
      out.write("    </div><!-- /tp-banner -->\r\n");
      out.write("  </div><!-- /tp-banner-container -->");
      out.write("<section class=\"section\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("    ");

      	if(request.getAttribute("perCatList") != null){
      		List<Perfume> perCatList = (List<Perfume>) request.getAttribute("perCatList");
      		if(perCatList.size() > 0){
      			
      out.write("<div class=\"row\">\n");
      out.write("      ");

      	for(Perfume perCat : perCatList){
      		
      out.write("<div class=\"col-sm-4\">\n");
      out.write("          <div class=\"text-center\">\n");
      out.write("            <div class=\"ad-box\">\n");
      out.write("              <div class=\"ad-box-text\">\n");
      out.write("                <p class=\"text-left\">");
      out.print(perCat.getCatPer().getCatPerfume() );
      out.write("</p>\n");
      out.write("                <h4>");
      out.print(perCat.getPerfumes() );
      out.write("</h4>\n");
      out.write("                <p class=\"text-right\">Khuyến mãi</p>\n");
      out.write("                <span class=\"tick\"><i class=\"flaticon-arrowhead7\"></i></span>\n");
      out.write("              </div><!-- /ad-box-inner -->\n");
      out.write("              ");

              	if(request.getAttribute("picPerCat"+perCat.getId()) != null){
              		Picture picPerCat = (Picture) request.getAttribute("picPerCat"+perCat.getId());
              		
      out.write("<figure>\n");
      out.write("              \t<img src=\"");
      out.print(request.getContextPath());
      out.write("/uploads/images/product/");
      out.print(picPerCat.getPicture());
      out.write("\"alt=\"image\"style=\"width:200px;height:200px;\">\n");
      out.write("              </figure>\n");
      out.write("              \t\t");

              	}else{
              		
      out.write("<figure>\n");
      out.write("              \t<img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/noimage.gif \"alt=\"image\"style=\"width:200px;height:200px;\">\n");
      out.write("              </figure>\n");
      out.write("              \t\t");

              	}
              
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/productsingle?id=");
      out.print(perCat.getId());
      out.write("\"></a>\n");
      out.write("            </div><!-- /ad-box -->\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      \t\t");

      	}
      
      out.write("</div>\n");
      out.write("      \t\t\t");

      		}
      	}
      
      out.write("<div class=\"features-list-box\">\n");
      out.write("        <ul class=\"feautes-list\">\n");
      out.write("          <li><a href=\"javascript:void(0)\">Giá Khuyến mãi</a></li>\n");
      out.write("          <li><a href=\"javascript:void(0)\">Ưu đãi giành riêng bạn</a></li>\n");
      out.write("          <li><a href=\"javascript:void(0)\">Thương hiệu độc quyền</a></li>\n");
      out.write("          <li><a href=\"javascript:void(0)\">Đặt hàng là có</a></li>\n");
      out.write("          <li><a href=\"javascript:void(0)\">Ship hàng nhanh</a></li>\n");
      out.write("        </ul><!-- /features-list -->\n");
      out.write("      </div><!-- /features-list-box -->\n");

	if(request.getAttribute("perfumeList") != null){
		List<Perfume> perfumeList = (List<Perfume>) request.getAttribute("perfumeList");
		if(perfumeList.size() > 0){
			
      out.write("<div class=\"row\">\n");
      out.write("\t");

		for(Perfume objEVA: perfumeList){
			
      out.write("<div class=\"col-sm-6 col-md-3\">\n");
      out.write("\t\t\t<div class=\"thumbnail thumbnail-product\">\n");
      out.write("\t\t\t");

				if(request.getAttribute("pic" + objEVA.getId()) != null){
					Picture pic = (Picture) request.getAttribute("pic" + objEVA.getId());
					String picture = pic.getPicture();
						
      out.write("<figure class=\"image-zoom\">\n");
      out.write("\t              <img src=\"");
      out.print(request.getContextPath());
      out.write("/uploads/images/product/");
      out.print(picture);
      out.write("\" alt=\"image\" style=\"width:200px;height:250px;\">\n");
      out.write("\t            </figure>\n");
      out.write("\t\t\t\t\t\t");

				}else{
					
      out.write("<figure class=\"image\">\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/noimage.gif\" alt=\"image\">\n");
      out.write("\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t");

				}
			
      out.write("<div class=\"caption text-center\">\n");
      out.write("\t\t\t\t\t<h5><a href=\"");
      out.print(request.getContextPath());
      out.write("/productsingle?id=");
      out.print(objEVA.getId());
      out.write('"');
      out.write('>');
      out.print(objEVA.getPerfumes() );
      out.write("</a></h5>\n");
      out.write("\t\t\t\t\t<div class=\"rating-star\">\n");
      out.write("\t\t\t\t\t\t<i class=\"flaticon-favourites7 selected\"></i>\n");
      out.write("\t\t\t\t\t\t<i class=\"flaticon-favourites7 selected\"></i>\n");
      out.write("\t\t\t\t\t\t<i class=\"flaticon-favourites7 selected\"></i>\n");
      out.write("\t\t\t\t\t\t<i class=\"flaticon-favourites7\"></i>\n");
      out.write("\t\t\t\t\t\t<i class=\"flaticon-favourites7\"></i>\n");
      out.write("\t\t\t\t\t</div><!-- /rating-star -->\n");
      out.write("\t\t\t\t\t<p class=\"prod-price text-primary\">$");
      out.print(objEVA.getMoney());
      out.write("</p>\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class = \"col-md-5\">\n");
      out.write("\t\t\t\t\t\t\t<button idPro=\"");
      out.print(objEVA.getId() );
      out.write("\" id=\"idpro-order\"type=\"button\" class=\"btn btn-info idpro-order\">\n");
      out.write("\t\t\t\t\t\t\t\tGiỏ hàng\n");
      out.write("\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class = \"col-md-5\">\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-success\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/addtocart?id=");
      out.print(objEVA.getId());
      out.write("\">Mua ngay</a>\n");
      out.write("\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t  </div><!-- /thumbail -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\t");

		}
	
      out.write("</div>\n");
      out.write("\t\t\t");

		}
	}


	if(request.getAttribute("proNews") != null){
		List<Perfume> proNews = (List<Perfume>) request.getAttribute("proNews");
		if(proNews.size() > 0){
			for(Perfume objProNew : proNews){
				
      out.write("<div class=\"tips-bar bg-primary\">\n");
      out.write("\t\t\t<p>Sản phẩm mới&nbsp;<strong>");
      out.print(objProNew.getPerfumes() );
      out.write(". </strong>");
      out.print(objProNew.getDescription());
      out.write("&nbsp;<strong>$");
      out.print(objProNew.getMoney() );
      out.write("</strong></p>\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/productsingle?id=");
      out.print(objProNew.getId() );
      out.write("\" class=\"read-more\">Đọc thêm</a>\n");
      out.write("\t\t</div> <!-- /tips-bar -->\n");
      out.write("\t\t\t\t");

			}
		}
	}


	if(request.getAttribute("perfumeListView") != null){
		List<Perfume> perfumeListView = (List<Perfume>)request.getAttribute("perfumeListView");
		if(perfumeListView.size() > 0){
			
      out.write("<header class=\"heading\">\n");
      out.write("\t\t\t<span class=\"caro-prev caro-featured-prev\"><i class=\"flaticon-arrowhead7\"></i></span>\n");
      out.write("\t\t\t<span class=\"caro-next caro-featured-next\"><i class=\"flaticon-arrow487\"></i></span>\n");
      out.write("\t\t\t<h4>Nước hoa nổi bật</h4>\n");
      out.write("\t\t</header>\n");
      out.write("\t\t\t");

			for(Perfume objPFLView : perfumeListView){
				
      out.write("<div class=\"carousel-single owl-carousel\" data-trans=\"backSlide\" data-btn-next=\"caro-featured-next\" data-btn-prev=\"caro-featured-prev\">\n");
      out.write("\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t<div class=\"featured-box\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-5\">\n");
      out.write("\t\t\t\t\t\t");

							if(request.getAttribute("picView"+objPFLView.getId()) != null){
								Picture picView = (Picture)request.getAttribute("picView"+objPFLView.getId());
								String picV = picView.getPicture();
								
      out.write("<figure class=\"image\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/uploads/images/product/");
      out.print(picV );
      out.write("\" alt=\"image\">\n");
      out.write("\t\t\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t\t\t\t");

							}else{
								
      out.write("<figure class=\"image\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/noimage.gif\" alt=\"image\">\n");
      out.write("\t\t\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t\t\t\t");

							}
						
      out.write("</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t\t <div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t\t<p>Thương hiệu: <a href=\"product-single.html\" class=\"text-primary\">");
      out.print(objPFLView.getBrand());
      out.write("</a></p>\n");
      out.write("\t\t\t\t\t\t\t\t<h4>Tên nước hoa: ");
      out.print(objPFLView.getPerfumes());
      out.write("</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href=\"");
      out.print(request.getContextPath());
      out.write("/productsingle?id=");
      out.print(objPFLView.getId());
      out.write("\" class=\"read-more text-primary\">Xem thông tin</a></p>\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href=\"#info-1\" data-toggle=\"collapse\">Khi nào tôi mới nhận được hàng, nếu tôi đặt ngay bây giờ? <i class=\"flaticon-small63\"></i></a></p>\n");
      out.write("\t\t\t\t\t\t\t\t  <div id=\"info-1\" class=\"collapse in\">\n");
      out.write("\t               \t\t\t\t\t<p>Sau 2 ngày sẽ có hàng</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Thời gian chỉ là gần đúng, ước tính theo thời gian giao hàng trước đó của các công ty vận chuyển.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" idPro=\"");
      out.print(objPFLView.getId() );
      out.write("\" class=\"btn btn-default idpro-order\">Thêm vào giỏ hàng</a>\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\n");
      out.write("               \t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div><!-- /featured-box -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");

				}
			

		}
	}

      out.write("</div><!-- /container -->\n");
      out.write("  </section><!-- /section -->\n");
      out.write("\n");
      out.write("\t<section class=\"section-sales section-image\" style=\"background-image:url(");
      out.print(request.getContextPath());
      out.write("/templates/public/images/resource/bgImg-1.jpg);\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-sm-9 col-sm-push-3 col-md-6 col-md-push-6 col-lg-5 col-lg-push-7 \">\n");
      out.write("\t\t\t\t\t<div class=\"promotion-box\">\n");
      out.write("\t\t\t\t\t\t<div class=\"text\">\n");
      out.write("\t\t\t\t\t\t\t<h4>Nước rửa mặt</h4>\n");
      out.write("\t\t\t\t\t\t\t<h3>Giảm giá</h3>\n");
      out.write("\t\t\t\t\t\t\t<h4>Lên đến <strong>70%</strong></h4>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<a href=\"promotions.html\" class=\"btn btn-default text-uppercase\">Mua ngay</a>\n");
      out.write("\t\t\t\t\t</div><!-- /promotion-box -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    document.getElementById(\"home\").classList.add('active-menu');\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("$(document).on(\"click\", \".idpro-order\", (function () {\n");
      out.write("\tvar idpro = $(this).attr(\"idpro\");\n");
      out.write("\t//lấy dữ liêu\n");
      out.write("\tswal.fire({\n");
      out.write("        title: 'Thêm sản phẩm vào giỏ hàng',\n");
      out.write("        text: \"Dữ liệu sẽ được cập nhật!\",\n");
      out.write("        icon: 'warning',\n");
      out.write("        padding: '3em',\n");
      out.write("        showCancelButton: true,\n");
      out.write("        confirmButtonColor: '#3085d6',\n");
      out.write("        cancelButtonColor: '#d33',\n");
      out.write("        confirmButtonText: 'Đồng ý!',\n");
      out.write("        cancelButtonText: 'Hủy bỏ',\n");
      out.write("        reverseButtons: true,\n");
      out.write("        customClass: null\n");
      out.write("    }).then((result) => {\n");
      out.write("    \t  if (result.value) {\n");
      out.write("    \t\t  $.ajax({\n");
      out.write("    \t\t\t  \tasync: false,\n");
      out.write("    \t            type: \"GET\",\n");
      out.write("    \t            url: \"");
      out.print(request.getContextPath());
      out.write("/addtocart\",\n");
      out.write("    \t            data: {id: idpro},\n");
      out.write("    \t            success: function (data) {\n");
      out.write("    \t            \tif(data==false){\n");
      out.write("\t    \t            \t\tSwal.fire(\n");
      out.write("   \t    \t                    'Thông Báo!',\n");
      out.write("   \t    \t                    'Không thành công.',\n");
      out.write("   \t    \t                    'danger'\n");
      out.write("   \t    \t                ).then(function () {\n");
      out.write("   \t    \t                    location.reload();\n");
      out.write("   \t    \t                })\n");
      out.write("    \t            \t}else{\n");
      out.write("   \t            \t\t\tSwal.fire(\n");
      out.write("\t            \t\t\t      'Thành công!',\n");
      out.write("\t            \t\t\t      'Thêm vào giỏ hàng thành công.',\n");
      out.write("\t            \t\t\t      'success'\n");
      out.write("\t            \t\t\t    ).then(function () {\n");
      out.write("   \t    \t                    \tlocation.reload();\n");
      out.write("   \t    \t                })\n");
      out.write("    \t            \t}\n");
      out.write("    \t            },\n");
      out.write("    \t            error: function (xhr, ajaxOptions, thrownError) {\n");
      out.write("    \t                Swal.fire(\n");
      out.write("    \t                    'Thông Báo!',\n");
      out.write("    \t                    'Thao tác không thể thực hiện.',\n");
      out.write("    \t                    'danger'\n");
      out.write("    \t                ).then(function () {\n");
      out.write("    \t                    location.reload();\n");
      out.write("    \t                })\n");
      out.write("    \t            }\n");
      out.write("    \t        });\n");
      out.write("    \t\t  } else if (result.dismiss === Swal.DismissReason.cancel) {\n");
      out.write("    \t\t    swal.fire(\n");
      out.write("    \t\t      'Thất bại',\n");
      out.write("    \t\t      'Bạn Chưa thực hiện thao tác này',\n");
      out.write("    \t\t      'error'\n");
      out.write("    \t\t    )\n");
      out.write("    \t\t  }\n");
      out.write("    \t\t})\n");
      out.write("}))\n");
      out.write("</script>\n");
      out.write("<section class=\"section footer-widgets bg-lighter-grey\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget widget-info\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"widget-heading-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><i class=\"flaticon-help\"></i>Câu hỏi?</h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<p>Liên hệ chúng tôi.</p>\r\n");
      out.write("\t\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"flaticon-phone72\"></i>0797 - 207 - 493</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"flaticon-email15\"></i>leducnam1805@gmail.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"flaticon-google125\"></i>Bạn có muốn nói chuyện trực tiếp?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget widget-info\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"widget-heading-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><i class=\"flaticon-shield90\"></i>Bảo mật</h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<p>Chính sách đơn giản.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Xác minh tính xác thực</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Bảo vệ quyền riêng tư</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget widget-info\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"widget-heading-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><i class=\"flaticon-shipping\"></i>Giao hàng</h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<p>Miễn phí khi mua 3 Sản phẩm.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Bao bì đẹp</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Kiểm tra hàng trước khi nhận</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget widget-info\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"widget-heading-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><i class=\"flaticon-creditcard21\"></i>Thanh toán</h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-cards\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo-visa.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo-americanexpress.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo-mastercard.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo-amazon.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/templates/public/images/logo-paypal.png\" alt=\"\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<footer class=\"site-footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("      <nav>\r\n");
      out.write("        <ul class=\"footer-links\">\r\n");
      out.write("          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/home\">Trang chủ</a></li>\r\n");
      out.write("          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/thuong-hieu\">Thương hiệu</a></li>\r\n");
      out.write("          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/blog\">Blog</a></li>\r\n");
      out.write("          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/lien-he\">Liên hệ</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</div><!-- /pageWrap -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"preloader-container\">\r\n");
      out.write("  <div id=\"loading-center-absolute\">\r\n");
      out.write("    <div class=\"object\" id=\"object_one\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_two\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_three\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_four\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_five\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_six\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_seven\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_eight\"></div>\r\n");
      out.write("    <div class=\"object\" id=\"object_big\"></div>\r\n");
      out.write("  </div><!-- /loading-center-absolute -->\r\n");
      out.write("</div><!-- /preloader-container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript\r\n");
      out.write("================================================== -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/plugins.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- revolution slider plugin -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/rs-plugin/js/jquery.themepunch.tools.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/public/js/rs-plugin/js/jquery.themepunch.revolution.min.js\"></script>\r\n");
      out.write("<!-- sweetalert -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/templates/admin/dist/node_modules/sweetalert2/dist/sweetalert2.all.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("  var revapi;\r\n");
      out.write("\r\n");
      out.write("  jQuery(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("       revapi = jQuery('.tp-banner').revolution({\r\n");
      out.write("\r\n");
      out.write("        dottedOverlay:\"none\",\r\n");
      out.write("        delay:9000,\r\n");
      out.write("        startwidth:1170,\r\n");
      out.write("        startheight:700,\r\n");
      out.write("        hideThumbs:200,\r\n");
      out.write("        \r\n");
      out.write("        thumbWidth:100,\r\n");
      out.write("        thumbHeight:50,\r\n");
      out.write("        thumbAmount:5,\r\n");
      out.write("        \r\n");
      out.write("        navigationType:\"none\",\r\n");
      out.write("        navigationArrows:\"solo\",\r\n");
      out.write("        navigationStyle:\"\",\r\n");
      out.write("        \r\n");
      out.write("        touchenabled:\"on\",\r\n");
      out.write("        onHoverStop:\"on\",\r\n");
      out.write("        \r\n");
      out.write("        swipe_velocity: 0.7,\r\n");
      out.write("        swipe_min_touches: 1,\r\n");
      out.write("        swipe_max_touches: 1,\r\n");
      out.write("        drag_block_vertical: false,\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("        keyboardNavigation:\"on\",\r\n");
      out.write("        \r\n");
      out.write("        navigationHAlign:\"center\",\r\n");
      out.write("        navigationVAlign:\"bottom\",\r\n");
      out.write("        navigationHOffset:0,\r\n");
      out.write("        navigationVOffset:20,\r\n");
      out.write("\r\n");
      out.write("        soloArrowLeftHalign:\"left\",\r\n");
      out.write("        soloArrowLeftValign:\"center\",\r\n");
      out.write("        soloArrowLeftHOffset:20,\r\n");
      out.write("        soloArrowLeftVOffset:0,\r\n");
      out.write("\r\n");
      out.write("        soloArrowRightHalign:\"right\",\r\n");
      out.write("        soloArrowRightValign:\"center\",\r\n");
      out.write("        soloArrowRightHOffset:20,\r\n");
      out.write("        soloArrowRightVOffset:0,\r\n");
      out.write("            \r\n");
      out.write("        shadow:0,\r\n");
      out.write("        fullWidth:\"on\",\r\n");
      out.write("        fullScreen:\"off\",\r\n");
      out.write("\r\n");
      out.write("        spinner:\"spinner0\",\r\n");
      out.write("        \r\n");
      out.write("        stopLoop:\"off\",\r\n");
      out.write("        stopAfterLoops:-1,\r\n");
      out.write("        stopAtSlide:-1,\r\n");
      out.write("\r\n");
      out.write("        shuffle:\"off\",\r\n");
      out.write("                            \r\n");
      out.write("        forceFullWidth:\"off\",           \r\n");
      out.write("        fullScreenAlignForce:\"off\",           \r\n");
      out.write("        minFullScreenHeight:\"400\",            \r\n");
      out.write("                    \r\n");
      out.write("        hideThumbsOnMobile:\"off\",\r\n");
      out.write("        hideNavDelayOnMobile:1500,            \r\n");
      out.write("        hideBulletsOnMobile:\"off\",\r\n");
      out.write("        hideArrowsOnMobile:\"off\",\r\n");
      out.write("        hideThumbsUnderResolution:0,\r\n");
      out.write("        \r\n");
      out.write("        hideSliderAtLimit:0,\r\n");
      out.write("        hideCaptionAtLimit:0,\r\n");
      out.write("        hideAllCaptionAtLilmit:0,\r\n");
      out.write("        startWithSlide:0,\r\n");
      out.write("        fullScreenOffsetContainer: \"\"\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("  }); //ready\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from wow-themes.com/demo/html/perfume/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 19 Aug 2015 06:49:09 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
